DROP TABLE IF EXISTS meta.aggregate CASCADE;
CREATE TABLE IF NOT EXISTS meta.aggregate (
    aggregate_name TEXT PRIMARY KEY,
    description    TEXT,
    numeric_flag   BOOLEAN,
    data_type      TEXT
);

TRUNCATE TABLE meta.aggregate;
INSERT INTO meta.aggregate(aggregate_name, description, numeric_flag, data_type)
VALUES ('any', 'Returns true if at least one value of `expr` is true.', FALSE, 'boolean'),
    ('approx_count_distinct', 'Returns the estimated cardinality by HyperLogLog++', FALSE, 'long'),
('approx_percentile', 'Returns the approximate `percentile` of the numeric column `col` which is the smallest value in the ordered `col` values (sorted from least to greatest) such that no more than `percentage` of `col` values is less than the value or equal to that value.', TRUE, 'decimal'),
    ('avg', 'Returns the mean calculated from values of a group.', TRUE, 'double'),
    ('bit_or', 'Returns the bitwise OR of all non-null input values, or null if none.', FALSE, 'boolean'),
    ('bit_xor', 'Returns the bitwise XOR of all non-null input values, or null if none.', FALSE, 'boolean'),
    ('bool_and', 'Returns true if all values of `expr` are true.', FALSE, 'boolean'),
    ('bool_or', 'Returns true if at least one value of `expr` is true.', FALSE, 'boolean'),
    ('collect_list', 'Collects and returns a list of non-unique elements', FALSE, 'array'),
    ('collect_set', 'Collects and returns a set of unique elements', FALSE, 'array'),
    ('corr', 'Returns Pearson coefficient of correlation between a set of number pairs.', TRUE, 'numeric'),
    ('count', 'Returns the number of rows for which the column expression is non-null.', FALSE, 'long'),
    ('count_if', 'Returns the number of `TRUE` values for the expression.', FALSE, 'long'),
('count_min_sketch', 'Returns a count-min sketch of a column with the given esp, confidence and seed. The result is an array of bytes, which can be deserialized to a `CountMinSketch` before usage. Count-min sketch is a probabilistic data structure used for cardinality estimation using sub-linear space.', FALSE, 'string'),
    ('covar_pop', 'Returns the population covariance of a set of number pairs.', TRUE, 'decimal'),
    ('covar_samp', 'Returns the sample covariance of a set of number pairs.', TRUE, 'decimal'),
    ('every', 'Returns true if all values of `expr` are true.', FALSE, 'boolean'),
    ('first', 'Returns the first value of column for a group of rows', FALSE, 'default'),
    ('first_value', 'Returns the first value of column for a group of rows', FALSE, 'default'),
    ('kurtosis', 'Returns the kurtosis value calculated from values of a group', TRUE, 'double'),
    ('last', 'Returns the last value of column for a group of rows', FALSE, 'default'),
    ('last_value', 'Returns the last value of column for a group of rows', FALSE, 'default'),
    ('max', 'Returns the maximum value of column', FALSE, 'default'),
    ('max_by', 'Returns the value of `x` associated with the maximum value of `y`.', FALSE, 'default'),
    ('mean', 'Returns the mean calculated from values of a group', TRUE, 'double'),
    ('min', 'Returns the minimum value of column', FALSE, 'default'),
    ('min_by', 'Returns the value of `x` associated with the minimum value of `y`.', FALSE, 'default'),
('percentile', 'Returns the exact percentile value of numeric column `col` at the given percentage. The value of percentage must be between 0.0 and 1.0. The value of frequency should be positive integral', TRUE, 'decimal'),
('percentile_approx', 'Returns the approximate percentile value of numeric column `col` at the given percentage. The value of percentage must be between 0.0 and 1.0. The `accuracy` parameter (default: 10000) is a positive numeric literal which controls approximation accuracy at the cost of memory. Higher value of `accuracy` yields better accuracy.', TRUE, 'decimal'),
    ('skewness', 'Returns the skewness value calculated from values of a group', TRUE, 'double'),
    ('some', 'Returns true if at least one value of `expr` is true.', FALSE, 'boolean'),
    ('std', 'Returns the sample standard deviation calculated from values of a group', TRUE, 'double'),
    ('stddev', 'Returns the sample standard deviation calculated from values of a group', TRUE, 'double'),
    ('stddev_pop', 'Returns the population standard deviation calculated from values of a group.', TRUE, 'double'),
    ('stddev_samp', 'Returns the sample standard deviation calculated from values of a group.', TRUE, 'double'),
    ('sum', 'Returns the sum calculated from values of a group.', TRUE, 'default'),
    ('var_pop', 'Returns the population variance calculated from values of a group', TRUE, 'double'),
    ('var_samp', 'Returns the sample variance calculated from values of a group.', TRUE, 'double'),
    ('variance', 'Returns the sample variance calculated from values of a group', TRUE, 'double')
;
